package net.babys_care.app.constants

import net.babys_care.app.AppManager
import net.babys_care.app.R

enum class Prefecture(val index: String, val value: String) {
    EMPTY("select_prefecture", AppManager.context.getString(R.string.select_prefecture)),
    HOKKAIDO    ("PREF01", AppManager.context.getString(R.string.hokkaido)),
    AOMORI      ("PREF02", AppManager.context.getString(R.string.aomori)),
    IWATE       ("PREF03", AppManager.context.getString(R.string.iwate)),
    MIYAGI      ("PREF04", AppManager.context.getString(R.string.miyagi)),
    AKITA       ("PREF05", AppManager.context.getString(R.string.akita)),
    YAMAGATA    ("PREF06", AppManager.context.getString(R.string.yamagata)),
    FUKUSHIMA   ("PREF07", AppManager.context.getString(R.string.fukushima)),
    IBARAKI     ("PREF08", AppManager.context.getString(R.string.ibaraki)),
    TOCHIGI     ("PREF09", AppManager.context.getString(R.string.tochigi)),
    GUNMA       ("PREF10", AppManager.context.getString(R.string.gunma)),
    SAITAMA     ("PREF11", AppManager.context.getString(R.string.saitama)),
    CHIBA       ("PREF12", AppManager.context.getString(R.string.chiba)),
    TOKYO       ("PREF13", AppManager.context.getString(R.string.tokyo)),
    KANAGAWA    ("PREF14", AppManager.context.getString(R.string.kagawa)),
    NIIGATA     ("PREF15", AppManager.context.getString(R.string.niigata)),
    TOYAMA      ("PREF16", AppManager.context.getString(R.string.toyama)),
    ISHIKAWA    ("PREF17", AppManager.context.getString(R.string.ishikawa)),
    FUKUI       ("PREF18", AppManager.context.getString(R.string.fukui)),
    YAMANASHI   ("PREF19", AppManager.context.getString(R.string.yamanashi)),
    NAGANO      ("PREF20", AppManager.context.getString(R.string.nagano)),
    GIFU        ("PREF21", AppManager.context.getString(R.string.gifu)),
    SHIZUOKA    ("PREF22", AppManager.context.getString(R.string.shizuoka)),
    AICHI       ("PREF23", AppManager.context.getString(R.string.aichi)),
    MIE         ("PREF24", AppManager.context.getString(R.string.mie)),
    SHIGA       ("PREF25", AppManager.context.getString(R.string.shiga)),
    KYOTO       ("PREF26", AppManager.context.getString(R.string.kyoto)),
    OSAKA       ("PREF27", AppManager.context.getString(R.string.osaka)),
    HYOGO       ("PREF28", AppManager.context.getString(R.string.hyogo)),
    NARA        ("PREF29", AppManager.context.getString(R.string.nara)),
    WAKAYAMA    ("PREF30", AppManager.context.getString(R.string.wakayama)),
    TOTTORI     ("PREF31", AppManager.context.getString(R.string.tottori)),
    SHIMANE     ("PREF32", AppManager.context.getString(R.string.shimane)),
    OKAYAMA     ("PREF33", AppManager.context.getString(R.string.okayama)),
    HIROSHIMA   ("PREF34", AppManager.context.getString(R.string.hiroshima)),
    YAMAGUCHI   ("PREF35", AppManager.context.getString(R.string.yamaguchi)),
    TOKUSHIMA   ("PREF36", AppManager.context.getString(R.string.tokushima)),
    KAGAWA      ("PREF37", AppManager.context.getString(R.string.kagawa)),
    EHIME       ("PREF38", AppManager.context.getString(R.string.ehime)),
    KOCHI       ("PREF39", AppManager.context.getString(R.string.kochi)),
    FUKUOKA     ("PREF40", AppManager.context.getString(R.string.fukushima)),
    SAGA        ("PREF41", AppManager.context.getString(R.string.saga)),
    NAGASAKI    ("PREF42", AppManager.context.getString(R.string.nagasaki)),
    KUMAMOTO    ("PREF43", AppManager.context.getString(R.string.kumamoto)),
    OITA        ("PREF44", AppManager.context.getString(R.string.oita)),
    MIYAZAKI    ("PREF45", AppManager.context.getString(R.string.miyagi)),
    KAGOSHIMA   ("PREF46", AppManager.context.getString(R.string.kagoshima)),
    OKINAWA     ("PREF47", AppManager.context.getString(R.string.okinawa))
}